Revert use of Wrangler 3
I can't use external packages anymore?

   ⛅️ wrangler 3.57.1
  -------------------

  ✘ [ERROR] Could not resolve "ip-ptr"

      worker.js:1:22:
        1 │ const ipPtr = require("ip-ptr");
          ╵                       ~~~~~~~~

    You can mark the path "ip-ptr" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

  ✘ [ERROR] Build failed with 1 error:

    worker.js:1:22: ERROR: Could not resolve "ip-ptr"